export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT';
export const GITHUB_USER_FETCH_REQUEST = 'GITHUB_USER_FETCH_REQUEST';
export const GITHUB_USER_FETCH_SUCCESS = 'GITHUB_USER_FETCH_SUCCESS';
export const GITHUB_USER_FETCH_FAILURE = 'GITHUB_USER_FETCH_FAILURE';